version: '3.9'
services:
  mongodb:
    container_name: inboxapi-mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/mongo-data
  
  rabbitmq:
    container_name: inboxapi-rabbitmq
    image: rabbitmq:3-management
    ports:
      - 8080:15672
      - 5672:5672
    volumes:
      - ./rabbitmq:/rabbitmq-data
  
  backend:
    container_name: inbox-api
    image: gustavoaraujo26/eventbus-inbox-api:latest
    ports:
      - 9000:9000
    depends_on:
      - mongodb
      - rabbitmq